### ISSUE TITLE
Skill french translation does not display

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-events#84]
When I input a french translation, it does not display in the translation list. However the translation is created and appears in IL.
It work fine for brazilian translations.

![2018-03-01_12-26-17](https://user-images.githubusercontent.com/6544411/36842379-cbbd1eec-1d4b-11e8-99bd-584f266a78be.gif)

**Comment by PierreAnctil** [comment]
Note that there is a workaround for editing translation that is to created a new french translation which seems to replace the previous one.

**Comment by fabian** [comment]
@PierreAnctil Right, that's because your browser has French already in the `Accept-Language`.

I've pushed now a fix in https://github.com/worldskills/worldskills-events/commit/92a257f9e10fa8ba8b8db40851e903bbe9b1f5f3 that's similar to what we did in the Infrastructure List by overriding the `Accept-Language` header.

Can you confirm the issue has been fixed?

**Comment by PierreAnctil** [comment]
That works a lot better :+1:
